/*
    Types that are not generated by backend schema but are used across multiple components
*/
import type { FlightWithFilesResponse } from '@schema';

export type BrushDataProps = {
    startIndex: number
    endIndex: number
    flightId: number
    startTimestamp: string
    endTimestamp: string
    intervalVisibleInChart: boolean
}


export enum FixedTimeIntervals {
    First30 = 'First 30s',
    Middle30 = 'Middle 30s',
    Last30 = 'Last 30s',
    Reset = 'Reset',
}


export enum TableType {
    FLIGHT = 'FLIGHT',
    MISSION = "MISSION",
    DRONE = "DRONE",
}


export type TableFlightSerializer = Omit<FlightWithFilesResponse, 'fkMission' | 'fkDrone'> & {
    fkMission: string | undefined
    fkDrone: string | undefined
    isSelectable?: boolean
    buttons?: undefined
}