"""Add apm parameter table

Revision ID: 08915c707628
Revises: e376a2158130
Create Date: 2022-11-29 11:25:54.388445

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "08915c707628"
down_revision = "e376a2158130"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apm_parameter_file",
        sa.Column("file_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_uri", sa.String(), nullable=True),
        sa.Column("flight_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flight.flight_id"],
        ),
        sa.PrimaryKeyConstraint("file_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("apm_parameter_file")
    # ### end Alembic commands ###
