"""Mission non nullable

Revision ID: 418a1b330108
Revises: 7b801feca009
Create Date: 2022-09-12 15:28:54.023863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "418a1b330108"
down_revision = "7b801feca009"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("flight", "plane_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("flight", "mission_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(
        "mission_details_description_key", "mission_details", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "mission_details_description_key", "mission_details", ["description"]
    )
    op.create_index("idx_flight_geo", "flight", ["geo"], unique=False)
    op.alter_column("flight", "mission_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("flight", "plane_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
