"""First migration

Revision ID: 4a681232eabd
Revises:
Create Date: 2022-07-11 17:30:00.290165

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4a681232eabd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mission_details",
        sa.Column("mission_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mission_alias", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column(
            "geo",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column("pilot", sa.String(), nullable=True),
        sa.Column("observer", sa.String(), nullable=True),
        sa.Column(
            "weather_conditions",
            sa.Enum(
                "sunny", "windy", "cloudy", "rainy", "snow", name="weathercondititions"
            ),
            nullable=True,
        ),
        sa.Column("temperature", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("mission_id"),
        sa.UniqueConstraint("description"),
        sa.UniqueConstraint("mission_alias"),
    )
    op.create_index(
        op.f("ix_mission_details_mission_id"),
        "mission_details",
        ["mission_id"],
        unique=False,
    )
    op.create_table(
        "plane_details",
        sa.Column("plane_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plane_alias", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("in_use", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("plane_id"),
        sa.UniqueConstraint("plane_alias"),
    )
    op.create_index(
        op.f("ix_plane_details_plane_id"), "plane_details", ["plane_id"], unique=False
    )
    op.create_table(
        "log_file",
        sa.Column("file_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("mission_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["mission_details.mission_id"],
        ),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_table(
        "plane_mission_association",
        sa.Column("plane_id", sa.Integer(), nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["mission_details.mission_id"],
        ),
        sa.ForeignKeyConstraint(
            ["plane_id"],
            ["plane_details.plane_id"],
        ),
        sa.PrimaryKeyConstraint("plane_id", "mission_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plane_mission_association")
    op.drop_table("log_file")
    op.drop_index(op.f("ix_plane_details_plane_id"), table_name="plane_details")
    op.drop_table("plane_details")
    op.drop_index(op.f("ix_mission_details_mission_id"), table_name="mission_details")
    op.drop_table("mission_details")
    # ### end Alembic commands ###
