"""Add telemetry file as separate entity

Revision ID: 7b801feca009
Revises: 9f96a8e16f9e
Create Date: 2022-08-26 13:09:34.274290

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b801feca009"
down_revision = "9f96a8e16f9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_file",
        sa.Column("tfile_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_uri", sa.String(), nullable=True),
        sa.Column("flight_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flight.flight_id"],
        ),
        sa.PrimaryKeyConstraint("tfile_id"),
    )
    op.drop_column("flight", "notes")
    op.add_column(
        "flight", sa.Column("notes", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("flight", "tfile_uri")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flight",
        sa.Column("tfile_uri", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_table("telemetry_file")
    # ### end Alembic commands ###
