"""Add rosbag table

Revision ID: e376a2158130
Revises: 418a1b330108
Create Date: 2022-11-21 20:09:30.959598

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e376a2158130"
down_revision = "418a1b330108"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rosbag_file",
        sa.Column("file_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_uri", sa.String(), nullable=True),
        sa.Column("flight_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flight.flight_id"],
        ),
        sa.PrimaryKeyConstraint("file_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rosbag_file")
    # ### end Alembic commands ###
