"""recreate flight file table

Revision ID: 0b5c7d44b4ce
Revises: f30108ceab9a
Create Date: 2023-04-05 14:43:40.980562

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0b5c7d44b4ce"
down_revision = "f30108ceab9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flight_file",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("fk_flight", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_flight"],
            ["flight.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flight_file_id"), "flight_file", ["id"], unique=False)
    op.add_column("flight", sa.Column("max_vertical_speed_down", sa.Float(), nullable=True))
    op.alter_column("flight", "avg_windspeed_kmg", new_column_name="avg_windspeed_kmh")
    op.drop_column("flight", "min_vertical_speed_down")
    op.drop_table("flight_files")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flight",
        sa.Column(
            "min_vertical_speed_down",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column("flight", "avg_windspeed_kmh", new_column_name="avg_windspeed_kmg")
    op.drop_column("flight", "max_vertical_speed_down")
    op.create_table(
        "flight_files",
        sa.Column("file_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("location", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("file_uri", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("flight_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["flight_id"], ["flight.id"], name="flight_files_flight_id_fkey"),
        sa.PrimaryKeyConstraint("file_uri", name="flight_files_pkey"),
    )
    op.drop_table("flight_file")
    # ### end Alembic commands ###
