"""create mavlink timeseries db

Revision ID: 10a897dc176b
Revises: c7f93ecc8c88
Create Date: 2023-05-19 19:45:09.209058

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10a897dc176b"
down_revision = "c7f93ecc8c88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mavlink_timeseries",
        sa.Column("fk_flight", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("message_type", sa.String(), nullable=False),
        sa.Column("message_field", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_flight"],
            ["flight.id"],
        ),
    )
    op.execute("create extension if not exists timescaledb cascade;")
    op.execute("SELECT create_hypertable('mavlink_timeseries', 'timestamp')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mavlink_timeseries")
    # ### end Alembic commands ###
