"""Update flight files table

Revision ID: 10b2207a3902
Revises: ce8df95b1870
Create Date: 2023-03-10 10:51:26.000272

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10b2207a3902"
down_revision = "ce8df95b1870"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.CreateSequence(sa.schema.Sequence("flight_files_id_seq")))
    op.add_column(
        "flight_files",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            server_default=sa.text("nextval('flight_files_id_seq'::regclass)"),
        ),
    )
    op.add_column("flight_files", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("flight_files", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("flight_files", sa.Column("fk_flight", sa.Integer(), nullable=True))
    op.create_primary_key("pk_flight_files", "flight_files", ["id", "version"])
    op.create_index(op.f("ix_flight_files_id"), "flight_files", ["id"], unique=False)
    op.drop_constraint("flight_files_flight_id_fkey", "flight_files", type_="foreignkey")
    op.create_foreign_key("flight_files_fk_flight_fkey", "flight_files", "flight", ["fk_flight"], ["id"])
    op.drop_column("flight_files", "flight_id")
    op.drop_column("flight_files", "file_uri")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flight_files", sa.Column("file_uri", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("flight_files", sa.Column("flight_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint("flight_files_fk_flight_fkey", "flight_files", type_="foreignkey")
    op.create_foreign_key("flight_files_flight_id_fkey", "flight_files", "flight", ["flight_id"], ["id"])
    op.drop_index(op.f("ix_flight_files_id"), table_name="flight_files")
    op.drop_column("flight_files", "fk_flight")
    op.drop_column("flight_files", "updated_at")
    op.drop_column("flight_files", "created_at")
    op.drop_column("flight_files", "id")
    # ### end Alembic commands ###
