"""update flight files table

Revision ID: 2c4a152370f0
Revises: f30108ceab9a
Create Date: 2023-04-04 12:40:13.397152

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c4a152370f0"
down_revision = "f30108ceab9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flight_files")
    op.create_table(
        "flight_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("fk_flight", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_flight"],
            ["flight.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flight_files")
    op.create_table(
        "flight_files",
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("file_uri", sa.String(), nullable=False),
        sa.Column("flight_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flight.id"],
        ),
        sa.PrimaryKeyConstraint("file_uri"),
        sa.UniqueConstraint("file_uri"),
    )
    # ### end Alembic commands ###
