"""add flight processing status columns

Revision ID: cea0b1eea5fe
Revises: 80f7539b8ca8
Create Date: 2024-02-12 21:51:53.237895

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from src.domain.flight.value_objects import FlightProcessingStatus

# revision identifiers, used by Alembic.
revision = "cea0b1eea5fe"
down_revision = "80f7539b8ca8"
branch_labels = None
depends_on = None
processing_status = postgresql.ENUM(FlightProcessingStatus, name="flightprocessingstatus")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    processing_status.create(op.get_bind(), checkfirst=True)
    op.add_column("flight", sa.Column("processing_status", processing_status, nullable=True))
    op.add_column("flight", sa.Column("processing_error_msg", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    processing_status.drop(op.get_bind())
    op.drop_column("flight", "processing_error_msg")
    op.drop_column("flight", "processing_status")
    # ### end Alembic commands ###
